config/routes.rb
Rails.application.routes.draw do
  get 'registrations/new'

  get 'sessions/new'

  root 'welcome#index'
  resources :kids_playdates
  resources :kids
  resources :playdates
  resources :parents
  resources :sessions, only: [:new, :create]
  delete 'sessions', to: "sessions#destroy"
  resources :registrations, only: [:new, :create]

  

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  belongs_to :parent
  has_many :playdates, through: :kids_playdates
  has_many :kids_playdates
end

app/models/kids_playdate.rb
class KidsPlaydate < ActiveRecord::Base
  belongs_to :kid
  belongs_to :playdate
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_secure_password
  has_many :kids
  has_many :playdates, through: :kids
end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  has_many :kids_playdates
  has_many :kids, through: :kids_playdates
  has_many :parents, through: :kids 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Parent.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def login_required
    redirect_to('/') if current_user.blank?
  end

  
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_filter :login_required
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show

  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :parent_id)
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_filter :login_required
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name, :gender)
    end
end

app/controllers/playdates_controller.rb
class PlaydatesController < ApplicationController
  before_filter :login_required
  before_action :set_playdate, only: [:show, :edit, :update, :destroy]

  # GET /playdates
  # GET /playdates.json
  def index
    @playdates = Playdate.all
  end

  # GET /playdates/1
  # GET /playdates/1.json
  def show
  end

  # GET /playdates/new
  def new
    @playdate = Playdate.new
  end

  # GET /playdates/1/edit
  def edit
  end

  # POST /playdates
  # POST /playdates.json
  def create
    @playdate = Playdate.new(playdate_params)

    respond_to do |format|
      if @playdate.save
        format.html { redirect_to @playdate, notice: 'Playdate was successfully created.' }
        format.json { render :show, status: :created, location: @playdate }
      else
        format.html { render :new }
        format.json { render json: @playdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playdates/1
  # PATCH/PUT /playdates/1.json
  def update
    respond_to do |format|
      if @playdate.update(playdate_params)
        format.html { redirect_to @playdate, notice: 'Playdate was successfully updated.' }
        format.json { render :show, status: :ok, location: @playdate }
      else
        format.html { render :edit }
        format.json { render json: @playdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playdates/1
  # DELETE /playdates/1.json
  def destroy
    @playdate.destroy
    respond_to do |format|
      format.html { redirect_to playdates_url, notice: 'Playdate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playdate
      @playdate = Playdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playdate_params
      params.require(:playdate).permit(:location, :kid_ids => [])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    #binding.pry
  end

  def create
    form_fields = params.permit(:name,:username, :gender, :password, :password_confirmation)
    @parent = Parent.new(form_fields)
    if @parent.save
      session[:user_id] = @parent.id
      redirect_to root_path, notice: "Thank you for signing up"
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @parent = Parent.new
  end

  def create
    @parent = Parent.find_by(username: params[:parent][:username])
    if @parent && @parent.authenticate(params[:parent][:password])
      session[:user_id] = @parent.id
      redirect_to root_path, notice: "You have been logged in!"
    else
      @parent = Parent.new
      flash.now[:error] = "Bad Username or Password"
      render :new
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "You have been logged out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/kids_playdates_helper.rb
module KidsPlaydatesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <label>Select a Parent</label><br>
   <%= f.collection_select :parent_id, Parent.all,:id,:name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.parent.name %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New Kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @kid.parent.name %>
</p>

<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playd8Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<center><%=image_tag("playd8_logo.png", alt: "Playd8 Logo")%></center>
  <% if flash[:error] %>
    <div>Error: <%= flash[:error] %></div>
  <% end %>

  <% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
  <% end %>

  <% if logged_in? %>
    Current user is: <%= current_user.name  %>
    <%= link_to "Log out", sessions_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_registration_path %> |
    <%= link_to "Sign in", new_session_path %>
  <% end %>

<%= yield %>
<div class="footer">
<p>Looking for Something? Click Below:</p>
* <a href=<%="/"%>>Home Page</a> * <a href=<%="/parents"%>>Current Parents</a>  * <a href=<%="/kids"%>>Current Kids</a>  * <a href=<%="/playdates"%>>Current Playdates</a>  *  <a href=<%="/kids/new"%>>Add a Kid</a>  *  <a href=<%="/playdates/new"%>>Make a Playdate</a> *
</div>
</body>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.radio_button :gender, 'mom' %> 
  <%= f.label :gender, 'Mom', :value => 'mom' %>
  <%= f.radio_button :gender, 'dad' %>
  <%= f.label :gender, 'Dad', :value => 'dad' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.gender %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<p>
  <strong>Kids:</strong>
  <% @parent.kids.each do |kid| %>
  <%= link_to kid.name, kid %>
  <% end %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>

app/views/playdates/_form.html.erb
<%= form_for(@playdate) do |f| %>
  <% if @playdate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playdate.errors.count, "error") %> prohibited this playdate from being saved:</h2>

      <ul>
      <% @playdate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
  <label>Who's Invited?</label><br>
  <%= f.collection_check_boxes :kid_ids, Kid.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playdates/edit.html.erb
<h1>Editing Playdate</h1>

<%= render 'form' %>

<%= link_to 'Show', @playdate %> |
<%= link_to 'Back', playdates_path %>

app/views/playdates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Playdates</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playdates.each do |playdate| %>
      <tr>
        <td><%= playdate.location %></td>
        <td><%= link_to 'Show', playdate %></td>
        <td><%= link_to 'Edit', edit_playdate_path(playdate) %></td>
        <td><%= link_to 'Destroy', playdate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playdate', new_playdate_path %>

app/views/playdates/new.html.erb
<h1>New Playdate</h1>

<%= render 'form' %>

<%= link_to 'Back', playdates_path %>

app/views/playdates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @playdate.location %>
</p>

<p>
  <strong>Playmates:</strong>
  <% @playdate.kids.each do |playmate| %>
  <%= link_to playmate.name, playmate %>
  <% end %>
</p>

<%= link_to 'Edit', edit_playdate_path(@playdate) %> |
<%= link_to 'Back', playdates_path %>

app/views/welcome/index.html.erb
<h2 align="center">Welcome to Playd8!</h2>
<p align="center">The premier web destination for arranging playdates with old and new friends</p>